"""add_emoji

Revision ID: 85c43fee74c3
Revises: 95000f9cf968
Create Date: 2024-08-22 14:03:21.675576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85c43fee74c3'
down_revision: Union[str, None] = '95000f9cf968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_log', sa.Column('emoji', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_log', 'emoji')
    # ### end Alembic commands ###
