"""add matches

Revision ID: c3633dece666
Revises: e957f96e8ca9
Create Date: 2024-08-27 22:12:07.406613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c3633dece666'
down_revision: Union[str, None] = 'e957f96e8ca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('player_a_id', sa.Integer(), nullable=True),
    sa.Column('player_b_id', sa.Integer(), nullable=True),
    sa.Column('score_player_a', sa.Integer(), nullable=True),
    sa.Column('score_player_b', sa.Integer(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('match_number', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_a_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_b_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('support_log', 'message',
                    existing_type=mysql.TEXT(collation='utf8mb4_bin'),
                    type_=sa.String(length=16384, collation='utf8mb4_bin'),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('support_log', 'message',
               existing_type=sa.String(length=16384, collation='utf8mb4_bin'),
               type_=mysql.TEXT(collation='utf8mb4_bin'),
               existing_nullable=True)
    op.drop_table('matches')
    # ### end Alembic commands ###
